// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD20zWvqYzSKxJDn4nx4iNyJ49YD7-_g64',
    appId: '1:747386089012:web:9ca10ef4cc5a272ce3a461',
    messagingSenderId: '747386089012',
    projectId: 'power-task-saas',
    authDomain: 'power-task-saas.firebaseapp.com',
    storageBucket: 'power-task-saas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvFUhUk4VNV-8bjC6Oen80AJNLPeblFCk',
    appId: '1:747386089012:android:745c0d1a30b51cc4e3a461',
    messagingSenderId: '747386089012',
    projectId: 'power-task-saas',
    storageBucket: 'power-task-saas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3q2z_E7tan3TLy8STZIFl8h4tQid2RNk',
    appId: '1:747386089012:ios:4a02f6860ecf07ece3a461',
    messagingSenderId: '747386089012',
    projectId: 'power-task-saas',
    storageBucket: 'power-task-saas.firebasestorage.app',
    iosBundleId: 'com.powertask.app',
  );

}